#' Function for visualizing trajectories generated by ZPDGrowthTrajectories
#'
#' \code{visualizeTrajectories} plots synthetic growth trajectories using \code{ggplot2}.
#'
#' @param trajectories An object of class \code{ZPD} produced by the \code{ZPDGrowthTrajectories()}
#'  function. If needed, this object be converted internally to "long" format suitable for
#'  \code{ggplot}.The function returns a \code{ggplot} object that can be modified with typical
#'  \code{ggplot2} arguments.
#'
#' @param assignment a vector indicating which school curriculum, if any, was provided during
#'  each time interval. If provided, vertical lines are added to indicate transitions. Defaults
#'  to NULL.
#'
#' @family visualizations
#'
#' @importFrom utils tail
#'
#' @export

visualizeTrajectories <- function(trajectories, assignment=NULL) {

  # check if trajectories is class ZPD, if not stop
  if(!("ZPD" %in% class(trajectories))) {stop("Object supplied to trajectories argument is not ZPDGrowthTrajectories() output")}

  # check to see if the trajectories are in long or wide format
  # if long, it will have 9 columns
  # if wide format, flip to long

  if (ncol(trajectories) != 9) {
    nstudents <- nrow(trajectories)
    times <- ncol(trajectories)-6

    trajectories <- reshape2::melt(trajectories, id.vars=1:6)
    trajectories[,7] <- rep(seq(1:times), each=nstudents)
    names(trajectories) <- c("id", "learn.rate", "home.env", "decay.rate", "initial.ach",
                             "curriculum", "time", "achievement")
    trajectories <- trajectories[order(trajectories$id),]
  }

  p <- ggplot2::ggplot(data=trajectories, ggplot2::aes(x=time, y=achievement, color=factor(id)))+
    ggplot2::geom_line(show.legend=FALSE, size=.5, alpha=.5) +
    ggplot2::geom_hline(yintercept=0, col="gray")+ggplot2::geom_vline(xintercept=0, col="gray")+
    ggplot2::theme(panel.background=ggplot2::element_blank(), panel.grid.major=ggplot2::element_blank(),
                   panel.grid.minor=ggplot2::element_blank())

  if (!is.null(assignment)) {

    # find transitions in the assignment object
    lag.assignment <- c(utils::tail(assignment,-1),NA)

    # index of those transitions, appending first and last time point / time
    index <- which(assignment != lag.assignment)

    p <- p + ggplot2::geom_vline(xintercept=index, alpha=.25)
  }

  return(p)
}
